import pandas as pd


data = pd.read_csv("flygut_cfus_2017-10-31_expts1345_totals.csv")
n = len(data.columns)

# Add all parameters (Taylor coefficients) as 0 in rows following the data:
for i in range(data.shape[0]):
        for j in range(n+2, n+34):
                data.set_value(i, j, 0)
data.rename(columns={n+2: "a", n+3: "a1", n+4: "a2", n+5: "a3", n+6: "a4", n+7: "a5",
        n+8: "b12", n+9: "b13", n+10: "b14", n+11: "b15", n+12: "b23", n+13: "b24",
        n+14: "b25", n+15: "b34", n+16: "b35", n+17: "b45", n+18: "c123", n+19: "c124",
        n+20: "c125", n+21: "c134", n+22: "c135", n+23: "c145", n+24: "c234", n+25: "c235",
        n+26: "c245", n+27: "c345", n+28: "d1234", n+29: "d1235", n+30: "d1245",
        n+31: "d1345", n+32: "d2345", n+33: "e12345"}, inplace=True)

# Change coefficients corresponding to present effects to 1:
for index, row in data.iterrows():
	combo = row["treat"]
	if combo == 1:
		data.set_value(index, "a", 1)
		data.set_value(index, "a1", 1)
	if combo == 2:
		data.set_value(index, "a", 1)
		data.set_value(index, "a2", 1)
	if combo == 3:
		data.set_value(index, "a", 1)
		data.set_value(index, "a3", 1)
	if combo == 4:
		data.set_value(index, "a", 1)
		data.set_value(index, "a4", 1)
	if combo == 5:
		data.set_value(index, "a", 1)
		data.set_value(index, "a5", 1)
	if combo == 6:
		data.set_value(index, "a", 1)
		data.set_value(index, "a1", 1)
		data.set_value(index, "a2", 1)
		data.set_value(index, "b12", 1)
	if combo == 7:
		data.set_value(index, "a", 1)
		data.set_value(index, "a1", 1)
		data.set_value(index, "a3", 1)
		data.set_value(index, "b13", 1)
	if combo == 8:
		data.set_value(index, "a", 1)
		data.set_value(index, "a1", 1)
		data.set_value(index, "a4", 1)
		data.set_value(index, "b14", 1)
	if combo == 9:
		data.set_value(index, "a", 1)
		data.set_value(index, "a1", 1)
		data.set_value(index, "a5", 1)
		data.set_value(index, "b15", 1)
	if combo == 10:
		data.set_value(index, "a", 1)
		data.set_value(index, "a2", 1)
		data.set_value(index, "a3", 1)
		data.set_value(index, "b23", 1)
	if combo == 11:
		data.set_value(index, "a", 1)
		data.set_value(index, "a2", 1)
		data.set_value(index, "a4", 1)
		data.set_value(index, "b24", 1)
	if combo == 12:
		data.set_value(index, "a", 1)
		data.set_value(index, "a2", 1)
		data.set_value(index, "a5", 1)
		data.set_value(index, "b25", 1)
	if combo == 13:
		data.set_value(index, "a", 1)
		data.set_value(index, "a3", 1)
		data.set_value(index, "a4", 1)
		data.set_value(index, "b34", 1)
	if combo == 14:
		data.set_value(index, "a", 1)
		data.set_value(index, "a3", 1)
		data.set_value(index, "a5", 1)
		data.set_value(index, "b35", 1)
	if combo == 15:
		data.set_value(index, "a", 1)
		data.set_value(index, "a4", 1)
		data.set_value(index, "a5", 1)
		data.set_value(index, "b45", 1)
	if combo == 16:
		data.set_value(index, "a", 1)
		data.set_value(index, "a1", 1)
		data.set_value(index, "a2", 1)
		data.set_value(index, "a3", 1)
		data.set_value(index, "b12", 1)
		data.set_value(index, "b13", 1)
		data.set_value(index, "b23", 1)
		data.set_value(index, "c123", 1)
	if combo == 17:
		data.set_value(index, "a", 1)
		data.set_value(index, "a1", 1)
		data.set_value(index, "a2", 1)
		data.set_value(index, "a4", 1)
		data.set_value(index, "b12", 1)
		data.set_value(index, "b14", 1)
		data.set_value(index, "b24", 1)
		data.set_value(index, "c124", 1)
	if combo == 18:
		data.set_value(index, "a", 1)
		data.set_value(index, "a1", 1)
		data.set_value(index, "a2", 1)
		data.set_value(index, "a5", 1)
		data.set_value(index, "b12", 1)
		data.set_value(index, "b15", 1)
		data.set_value(index, "b25", 1)
		data.set_value(index, "c125", 1)
	if combo == 22:
		data.set_value(index, "a", 1)
		data.set_value(index, "a2", 1)
		data.set_value(index, "a3", 1)
		data.set_value(index, "a4", 1)
		data.set_value(index, "b23", 1)
		data.set_value(index, "b24", 1)
		data.set_value(index, "b34", 1)
		data.set_value(index, "c234", 1)
	if combo == 25:
		data.set_value(index, "a", 1)
		data.set_value(index, "a3", 1)
		data.set_value(index, "a4", 1)
		data.set_value(index, "a5", 1)
		data.set_value(index, "b34", 1)
		data.set_value(index, "b35", 1)
		data.set_value(index, "b45", 1)
		data.set_value(index, "c345", 1)
	if combo == 19:
		data.set_value(index, "a", 1)
		data.set_value(index, "a1", 1)
		data.set_value(index, "a3", 1)
		data.set_value(index, "a4", 1)
		data.set_value(index, "b13", 1)
		data.set_value(index, "b14", 1)
		data.set_value(index, "b34", 1)
		data.set_value(index, "c134", 1)
	if combo == 20:
		data.set_value(index, "a", 1)
		data.set_value(index, "a1", 1)
		data.set_value(index, "a3", 1)
		data.set_value(index, "a5", 1)
		data.set_value(index, "b13", 1)
		data.set_value(index, "b15", 1)
		data.set_value(index, "b35", 1)
		data.set_value(index, "c135", 1)
	if combo == 21:
		data.set_value(index, "a", 1)
		data.set_value(index, "a1", 1)
		data.set_value(index, "a4", 1)
		data.set_value(index, "a5", 1)
		data.set_value(index, "b14", 1)
		data.set_value(index, "b15", 1)
		data.set_value(index, "b45", 1)
		data.set_value(index, "c145", 1)
	if combo == 24:
		data.set_value(index, "a", 1)
		data.set_value(index, "a2", 1)
		data.set_value(index, "a4", 1)
		data.set_value(index, "a5", 1)
		data.set_value(index, "b24", 1)
		data.set_value(index, "b25", 1)
		data.set_value(index, "b45", 1)
		data.set_value(index, "c245", 1)
	if combo == 23:
		data.set_value(index, "a", 1)
		data.set_value(index, "a2", 1)
		data.set_value(index, "a3", 1)
		data.set_value(index, "a5", 1)
		data.set_value(index, "b23", 1)
		data.set_value(index, "b25", 1)
		data.set_value(index, "b35", 1)
		data.set_value(index, "c235", 1)
	if combo == 26:
		data.set_value(index, "a", 1)
		data.set_value(index, "a1", 1)
		data.set_value(index, "a2", 1)
		data.set_value(index, "a3", 1)
		data.set_value(index, "a4", 1)
		data.set_value(index, "b12", 1)
		data.set_value(index, "b13", 1)
		data.set_value(index, "b14", 1)
		data.set_value(index, "b23", 1)
		data.set_value(index, "b24", 1)
		data.set_value(index, "b34", 1)
		data.set_value(index, "c123", 1)
		data.set_value(index, "c124", 1)
		data.set_value(index, "c134", 1)
		data.set_value(index, "c234", 1)
		data.set_value(index, "d1234", 1)
	if combo == 27:
		data.set_value(index, "a", 1)
		data.set_value(index, "a1", 1)
		data.set_value(index, "a2", 1)
		data.set_value(index, "a3", 1)
		data.set_value(index, "a5", 1)
		data.set_value(index, "b12", 1)
		data.set_value(index, "b13", 1)
		data.set_value(index, "b15", 1)
		data.set_value(index, "b23", 1)
		data.set_value(index, "b25", 1)
		data.set_value(index, "b35", 1)
		data.set_value(index, "c123", 1)
		data.set_value(index, "c125", 1)
		data.set_value(index, "c135", 1)
		data.set_value(index, "c235", 1)
		data.set_value(index, "d1235", 1)
	if combo == 28:
		data.set_value(index, "a", 1)
		data.set_value(index, "a1", 1)
		data.set_value(index, "a2", 1)
		data.set_value(index, "a4", 1)
		data.set_value(index, "a5", 1)
		data.set_value(index, "b12", 1)
		data.set_value(index, "b14", 1)
		data.set_value(index, "b15", 1)
		data.set_value(index, "b24", 1)
		data.set_value(index, "b25", 1)
		data.set_value(index, "b45", 1)
		data.set_value(index, "c124", 1)
		data.set_value(index, "c125", 1)
		data.set_value(index, "c145", 1)
		data.set_value(index, "c245", 1)
		data.set_value(index, "d1245", 1)
	if combo == 29:
		data.set_value(index, "a", 1)
		data.set_value(index, "a1", 1)
		data.set_value(index, "a3", 1)
		data.set_value(index, "a4", 1)
		data.set_value(index, "a5", 1)
		data.set_value(index, "b13", 1)
		data.set_value(index, "b14", 1)
		data.set_value(index, "b15", 1)
		data.set_value(index, "b34", 1)
		data.set_value(index, "b35", 1)
		data.set_value(index, "b45", 1)
		data.set_value(index, "c134", 1)
		data.set_value(index, "c135", 1)
		data.set_value(index, "c145", 1)
		data.set_value(index, "c345", 1)
		data.set_value(index, "d1345", 1)
	if combo == 30:
		data.set_value(index, "a", 1)
		data.set_value(index, "a2", 1)
		data.set_value(index, "a3", 1)
		data.set_value(index, "a4", 1)
		data.set_value(index, "a5", 1)
		data.set_value(index, "b23", 1)
		data.set_value(index, "b24", 1)
		data.set_value(index, "b25", 1)
		data.set_value(index, "b34", 1)
		data.set_value(index, "b35", 1)
		data.set_value(index, "b45", 1)
		data.set_value(index, "c234", 1)
		data.set_value(index, "c235", 1)
		data.set_value(index, "c245", 1)
		data.set_value(index, "c345", 1)
		data.set_value(index, "d2345", 1)
	if combo == 31:
		data.set_value(index, "a", 1)
		data.set_value(index, "a1", 1)
		data.set_value(index, "a2", 1)
		data.set_value(index, "a3", 1)
		data.set_value(index, "a4", 1)
		data.set_value(index, "a5", 1)
		data.set_value(index, "b12", 1)
		data.set_value(index, "b13", 1)
		data.set_value(index, "b14", 1)
		data.set_value(index, "b15", 1)
		data.set_value(index, "b23", 1)
		data.set_value(index, "b24", 1)
		data.set_value(index, "b25", 1)
		data.set_value(index, "b34", 1)
		data.set_value(index, "b35", 1)
		data.set_value(index, "b45", 1)
		data.set_value(index, "c123", 1)
		data.set_value(index, "c124", 1)
		data.set_value(index, "c125", 1)
		data.set_value(index, "c134", 1)
		data.set_value(index, "c135", 1)
		data.set_value(index, "c145", 1)
		data.set_value(index, "c234", 1)
		data.set_value(index, "c235", 1)
		data.set_value(index, "c245", 1)
		data.set_value(index, "c345", 1)
		data.set_value(index, "d1234", 1)
		data.set_value(index, "d1235", 1)
		data.set_value(index, "d1245", 1)
		data.set_value(index, "d1345", 1)
		data.set_value(index, "d2345", 1)
		data.set_value(index, "e12345", 1)
	if combo == 32:
		data.set_value(index, "a", 1)
data.to_csv("flygut_cfus_201710-31_expts1345_totals_processed.csv")
